sudo: required

env:
  - DOCKER_COMPOSE_VERSION=1.18.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - cp .env.dist .env

services:
  - docker

script:
  - ./deploy/build.sh
  - ./deploy/up.sh
  - ./deploy/exec.sh composer install
  - ./deploy/exec.sh ./bin/phpunit
  
after_script:
  - bash <(curl -s https://codecov.io/bash)
  - docker-compose -f deploy/docker-compose.yml down
